### PR TITLE
Create info.txt

### PR DESCRIPTION
**Pull request by Jarvismahesh**
Plz Verify my Code.

### CODE REVIEW

**Review by Jeban11 — CHANGES_REQUESTED** [review]
Please remove your unused imports in bean class

**Comment by Jarvismahesh** [comment]
Plz verify again, I resolved my issue.

**Comment by Jarvismahesh** [comment]
Plz verify again,I fixed that issue.

**Comment by Jeban11** [comment]
Hi Mahesh,I  verified your code no bugs here...

**Comment by Jarvismahesh** [comment]
Thanks..

**Pull request merged**
